Added exoplanets project
pyviz-topics/examples pull request #159
Opened 2021-06-21 15:48 UTC by ablythed

Identical PR to https://github.com/pyviz-topics/examples/pull/156 except now basing the PR on a branch instead of master.

2021-07-06 20:20 UTC, jbednar requested changes
Cool! Remaining to-do items that I can see:

- [x] Define downloads
- [x] Add test data
- [x] Briefly show raw data and explain that it needs projecting
- [x] Change default deployment command in the anaconda-project commands list to the dashboard
- [x] Flesh out caching to cover all memory-using chunks
- [x] Replace @pn.depends with pn.bind, moving widget definitions later in the file
- [x] Illustrate the usage of functions like radius_mass _before_ putting them in a panel
- [ ] Collect all or at least most widgets into a list `widgets` before displaying them with `pn.Column(widgets)`

2021-07-23 18:16 UTC, ablythed commented
@jbednar Thanks for the help. It should be ready for another look!

2021-08-03 04:02 UTC, jbednar commented
Looks great!  I'll have some edits, but as this is on a branch separate from the repo I'll go ahead and merge this and start a new PR for the edits.

2021-08-03 04:02 UTC, jbednar approved these changes

2021-08-03 04:02 UTC, merged